# -*- coding: utf-8 -*-
"""Task_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_lHCfhoplQhihjsI5INIO8XR29qtJs-L
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df5=pd.read_csv('/content/sample_data/RTA Dataset.csv')
df5.head()
df5.describe()

df5.isnull().sum()

df5.bfill(inplace=True)
df5.isnull().sum()

df5['Hour']=pd.to_datetime(df5['Time'],format='%H:%M:%S').dt.hour

plt.figure(figsize=(8,4))
sns.countplot(x='Hour',data=df5, hue='Hour', palette='viridis',legend=False)
plt.title('Number of Accidents per Hour')
plt.xlabel('Hour Of The Day')
plt.ylabel('Number of Accidents')
plt.show()

plt.figure(figsize=(8,4))
sns.countplot(x='Day_of_week',data=df5, hue='Day_of_week', palette='viridis',legend=False)
plt.title('Number of Accidents by Day of the Week')
plt.xlabel('Day of the Week')
plt.ylabel('Number of Accidents')
plt.show()

plt.figure(figsize=(8,4))
sns.countplot(x='Age_band_of_driver', hue='Age_band_of_driver',data=df5, palette='viridis')
plt.title('Number of Accidents by Day of the Week')
plt.xlabel('Age Band of Driver')
plt.ylabel('Number of Accidents')
plt.show()

plt.figure(figsize=(8,4))
sns.countplot(x='Type_of_vehicle', hue='Type_of_vehicle',data=df5, palette='viridis')
plt.title('Number of Accidents by Day of the Week')
plt.xlabel('Type of Vehicle')
plt.ylabel('Number of Accidents')
plt.xticks(rotation=65, ha='right')
plt.show()

plt.figure(figsize=(8,4))
sns.countplot(y='Cause_of_accident',data=df5,palette='viridis', hue='Cause_of_accident',order=df5['Cause_of_accident'].value_counts().index)
plt.title('Cause of Accidents')
plt.xlabel('Number of Accidents')
plt.ylabel('Cause of Accident')
plt.show()